version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 6
  file-lines:
    enabled: true
    config:
      threshold: 500
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 40
  method-lines:
    enabled: true
    config:
      threshold: 40
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 8
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 1.8
