package info.peperkoek.databaselibrary.testutils;

import info.peperkoek.databaselibrary.annotations.*;
import java.util.Objects;

/**
 *
 * @author Rick Pijnenburg - REXOTIUM
 */
@Entity(tableName = "objecten")
public class ForeignObject {
    @PrimaryKey
    @AutoGenerated
    private Integer id;
    private String name;
    private DataObject object;

    public Integer getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public DataObject getObject() {
        return object;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setObject(DataObject object) {
        this.object = object;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        hash = 97 * hash + Objects.hashCode(this.name);
        hash = 97 * hash + Objects.hashCode(this.object);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final ForeignObject other = (ForeignObject) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        return Objects.equals(this.object, other.object);
    }
}