package info.peperkoek.databaselibrary.testutils;

import info.peperkoek.databaselibrary.annotations.*;
import java.util.Objects;

/**
 *
 * @author Rick Pijnenburg - REXOTIUM
 */
public class LinkObject {
    @PrimaryKey
    @AutoGenerated
    private Integer id;
    @Map(mapping = "optionName")
    private String option;
    @Map(mapping = "active")
    private Boolean on;

    public Integer getId() {
        return id;
    }

    public String getOption() {
        return option;
    }

    public Boolean isOn() {
        return on;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setOption(String option) {
        this.option = option;
    }

    public void setOn(Boolean on) {
        this.on = on;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.id);
        hash = 79 * hash + Objects.hashCode(this.option);
        hash = 79 * hash + Objects.hashCode(this.on);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LinkObject other = (LinkObject) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        if (!Objects.equals(this.on, other.on)) {
            return false;
        }
        return Objects.equals(this.option, other.option);
    }
}